services:  
  phase1_db:
    image : bitnami/cassandra:latest
    container_name : phase1_db
    volumes :
      - ./database/scripts:/docker-entrypoint-initdb.d
      - cassandra_data:/bitnami
    ports:
      - "9042:9042"
      - "7000:7000"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 60s
      timeout: 10s
      retries: 10
  backend:
    image : phase1/backend
    container_name : phase1_backend
    build :
      context : ./backend/
      dockerfile: dockerfile
    environment:
      SPRING_DATA_CASSANDRA_CONTACT_POINTS: phase1_db
    ports:
      - "8080:8080"
    depends_on:
      phase1_db:
        condition: service_healthy
    restart: always
  frontend:
    image : phase1/frontend
    container_name : phase1_frontend
    build : 
      context : ./frontend/
      dockerfile: dockerfile
    ports :
      - "3000:3000"
    depends_on:
      phase1_db:
        condition: service_healthy

volumes:
  cassandra_data : {}

networks:
  default:
    driver: bridge